version: '3.7'

services:
  web:
    build:
      context: .
    command: /bin/sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ./tickets:/tickets
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"

volumes:
  postgres_data: